wallpaper {
    monitor = DP-1
    path = /home/eduayala/.config/wallpapers/catppuccin-wallpapers/landscapes/tropic_island_night.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/eduayala/.config/wallpapers/catppuccin-wallpapers/landscapes/tropic_island_night.jpg
    fit_mode = cover
}

splash = false
